<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>$(NetFrameworkTestVersion)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Quartz.Serialization.Newtonsoft" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Akka.TestKit.Xunit" />
    <PackageReference Include="EntityFramework" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <!-- <PackageReference Include="Microsoft.Data.Sqlite.Core" /> -->
  </ItemGroup>
  <ItemGroup>
    <Content Include="tables_sqlite.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Akka.Quartz.Actor\Akka.Quartz.Actor.csproj" />
  </ItemGroup>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>