<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>$(NetFrameworkTestVersion)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Akka.TestKit.Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akka.Quartz.Actor\Akka.Quartz.Actor.csproj" />
  </ItemGroup>
  
</Project>